<?php /* @var $this Controller */Yii::app()->bootstrap->register();?><!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>后台管理</title><meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta name="description" content=""><meta name="author" content=""><link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl;?>/lib/datepicker/css/datepicker.css"><link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl;?>/lib/jquery-ui/css/ui-lightness/jquery-ui-1.10.3.custom.css"><link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl;?>/stylesheets/theme.css"><link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->theme->baseUrl;?>/stylesheets/font-awesome-ie7.css"><!-- Demo page code --><style type="text/css">#line-chart {	height: 300px;	width: 800px;	margin: 0px auto;	margin-top: 1em;}
.brand {	font-family: georgia, serif;}
.brand .first {	color: #ccc;	font-style: italic;}
.brand .second {	color: #fff;	font-weight: bold;}</style>
</head>
<body class="">    <div class="navbar">        <div class="navbar-inner">            <ul class="nav pull-right">                <li><a href="<?php echo Yii::app()->homeUrl?>/../../index.php" class="hidden-phone  visible-desktop" role="button">进入前台</a></li>                <li id="fat-menu" class="dropdown">                    <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">                        <i class="icon-user"></i>                        <?php echo Yii::app()->user->name?>                        <i class="icon-caret-down"></i>                    </a>                    <ul class="dropdown-menu">                        <li>                            <a tabindex="-1" href="<?php echo Yii::app()->createUrl('user/passwordupdate');?>">修改密码</a>                        </li>                        <li class="divider"></li>                        <li>                            <a tabindex="-1" href="<?php echo Yii::app()->createUrl('site/logout');?>">退出</a>                        </li>                    </ul>                </li>            </ul>            <a class="brand" href="<?php echo Yii::app()->homeUrl;?>">                <span class="first">后台</span> <span class="second">管理中心</span>            </a>
        </div>
    </div>	
    <div class="sidebar-nav">                <?php if(Yii::app()->user->checkAccess('admin') || Yii::app()->user->checkAccess('manager')): ?>                <a href="#user-menu" class="nav-header collapsed" data-toggle="collapse">员工管理</a>        <ul id="user-menu" class="nav nav-list collapse">            <li>                <a href="<?php echo Yii::app()->createUrl('user/index',array('menu'=>0));?>">员工列表</a>            </li>            <li>                <a href="<?php echo Yii::app()->createUrl('user/create',array('menu'=>0));?>">添加员工</a>            </li>        </ul>                <?php  endif;?>                <?php if(Yii::app()->user->checkAccess('admin')): ?>                <a href="#customer-menu" class="nav-header collapsed" data-toggle="collapse">车主管理</a>        <ul id="customer-menu" class="nav nav-list collapse">            <li>                <a href="<?php echo Yii::app()->createUrl('user/customers',array('menu'=>1));?>">车主列表</a>            </li>            <li>                <a href="<?php echo Yii::app()->createUrl('user/createcustomer',array('menu'=>1));?>">添加车主</a>            </li>        </ul>                <?php  endif;?>        
    </div>
    <?php if(!empty($this->breadcrumbs)):?>        <div class="content">        <div class="header">            <h1 class="page-title">                <?php echo $this->pageTitle?>            </h1>        </div>                <?php $this->widget('bootstrap.widgets.TbBreadcrumbs', array(                'links'=>$this->breadcrumbs,                ));        ?>        <!-- breadcrumbs -->        <div class="container-fluid">            <div class="row-fluid">                <?php echo $content;?>            </div>        </div>    </div>        <?php else:?>        <?php echo $content;?>
    <?php endif;?>
    <script src="<?php echo Yii::app()->theme->baseUrl;?>/lib/jquery-ui/js/jquery-ui-1.10.3.custom.js"></script>    <script src="<?php echo Yii::app()->theme->baseUrl;?>/lib/jquery-ui/js/jquery.ui.datepicker-zh-CN.min.js"></script>    <script type="text/javascript">        $("[rel=tooltip]").tooltip();        $(function() {            $('.demo-cancel-click').click(function(){return false;});            $('body').on('focus',".datepicker", function(){                    $(this).removeClass('hasDatepicker');                    $(this).datepicker({changeMonth:true,changeYear:true});            });            var menu='';            <?php if(isset($_GET['menu'])){?>            menu=<?php echo $_GET['menu'];?>;            $('.sidebar-nav ul:eq('+menu+')').addClass('in');            //$('.sidebar-nav ul:not('+menu+')').removeClass('in');            <?php }?>        });            </script></body></html>